---
- name: Install prerequisites on all Kubernetes nodes
  hosts: kubeadm
  become: true
  tasks:
    - name: Disable swap
      command: swapoff -a
      changed_when: true

    - name: Remove swap entries from /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^/swapfile|^.*\sswap\s'
        state: absent
      register: fstab_swap
      changed_when: fstab_swap.changed

    - name: Remove swap file if exists
      file:
        path: /swapfile
        state: absent
      changed_when: true

    - name: Stop and disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Install required packages for Docker
      dnf:
        name:
          - dnf-plugins-core
        state: present

    - name: Add Docker repository
      get_url:
        url: https://download.docker.com/linux/fedora/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: '0644'

    - name: Install Docker and containerd
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Ensure containerd config directory exists
      file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Configure containerd for CRI
      copy:
        dest: /etc/containerd/config.toml
        content: |
          version = 2
          [plugins]
            [plugins."io.containerd.grpc.v1.cri"]
              sandbox_image = "registry.k8s.io/pause:3.10"
              [plugins."io.containerd.grpc.v1.cri".containerd]
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
                  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                    runtime_type = "io.containerd.runc.v2"
                    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                      SystemdCgroup = true
        mode: '0644'
      notify: Restart containerd

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Start and enable containerd service
      service:
        name: containerd
        state: started
        enabled: yes

    - name: Add Kubernetes repository
      copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://pkgs.k8s.io/core:/stable:/v1.33/rpm/
          enabled=1
          gpgcheck=1
          gpgkey=https://pkgs.k8s.io/core:/stable:/v1.33/rpm/repodata/repomd.xml.key
        mode: '0644'

    - name: Install Kubernetes tools
      dnf:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present

    - name: Start and enable kubelet service
      service:
        name: kubelet
        state: started
        enabled: yes

  handlers:
    - name: Restart containerd
      service:
        name: containerd
        state: restarted


